In [318]:
import importlib
from functools import partial

from torch import nn
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd
import copy


from decision_learning.data.shortest_path_grid import genData
from decision_learning.modeling.loss import SPOPlus
from decision_learning.modeling.models import LinearRegression
from decision_learning.modeling.val_metrics import decision_regret
from decision_learning.modeling.train import train, calc_test_regret, init_loss_data_pretraining, filter_kwargs

In [23]:
# Only for on the fly reloading of changing modules
# import decision_learning.data.shortest_path_grid
# importlib.reload(decision_learning.data.shortest_path_grid)
# import decision_learning.modeling.val_metrics
# importlib.reload(decision_learning.modeling.val_metrics)

# import decision_learning.modeling.models
# importlib.reload(decision_learning.modeling.models)
# from decision_learning.modeling.models import LinearRegression
# import decision_learning.modeling.loss
# importlib.reload(decision_learning.modeling.loss)
# from decision_learning.modeling.loss import SPOPlus
# import decision_learning.modeling.train
# importlib.reload(decision_learning.modeling.train)
# from decision_learning.modeling.train import train, calc_test_regret

<module 'decision_learning.modeling.train' from '/home1/yongpeng/decision-focused-learning/src/decision_learning/modeling/train.py'>

# Optimization Solver

In [105]:
def shortest_path_solver(costs, size, sens = 1e-4):
    # Forward Pass
    starting_ind = 0
    starting_ind_c = 0
    samples = costs.shape[0]
    V_arr = torch.zeros(samples, size ** 2)
    for i in range(0, 2 * (size - 1)):
        num_nodes = min(i + 1, 9 - i)
        num_nodes_next = min(i + 2, 9 - i - 1)
        num_arcs = 2 * (max(num_nodes, num_nodes_next) - 1)
        V_1 = V_arr[:, starting_ind:starting_ind + num_nodes]
        layer_costs = costs[:, starting_ind_c:starting_ind_c + num_arcs]
        l_costs = layer_costs[:, 0::2]
        r_costs = layer_costs[:, 1::2]
        next_V_val_l = torch.ones(samples, num_nodes_next) * float('inf')
        next_V_val_r = torch.ones(samples, num_nodes_next) * float('inf')
        if num_nodes_next > num_nodes:
            next_V_val_l[:, :num_nodes_next - 1] = V_1 + l_costs
            next_V_val_r[:, 1:num_nodes_next] = V_1 + r_costs
        else:
            next_V_val_l = V_1[:, :num_nodes_next] + l_costs
            next_V_val_r = V_1[:, 1:num_nodes_next + 1] + r_costs
        next_V_val = torch.minimum(next_V_val_l, next_V_val_r)
        V_arr[:, starting_ind + num_nodes:starting_ind + num_nodes + num_nodes_next] = next_V_val

        starting_ind += num_nodes
        starting_ind_c += num_arcs

    # Backward Pass
    starting_ind = size ** 2
    starting_ind_c = costs.shape[1]
    prev_act = torch.ones(samples, 1)
    sol = torch.zeros(costs.shape)
    for i in range(2 * (size - 1), 0, -1):
        num_nodes = min(i + 1, 9 - i)
        num_nodes_next = min(i, 9 - i + 1)
        V_1 = V_arr[:, starting_ind - num_nodes:starting_ind]
        V_2 = V_arr[:, starting_ind - num_nodes - num_nodes_next:starting_ind - num_nodes]

        num_arcs = 2 * (max(num_nodes, num_nodes_next) - 1)
        layer_costs = costs[:, starting_ind_c - num_arcs: starting_ind_c]

        if num_nodes < num_nodes_next:
            l_cs_res = ((V_2[:, :num_nodes_next - 1] - V_1 + layer_costs[:, ::2]) < sens) * prev_act
            r_cs_res = ((V_2[:, 1:num_nodes_next] - V_1 + layer_costs[:, 1::2]) < sens) * prev_act
            prev_act = torch.zeros(V_2.shape)
            prev_act[:, :num_nodes_next - 1] += l_cs_res
            prev_act[:, 1:num_nodes_next] += r_cs_res
        else:
            l_cs_res = ((V_2 - V_1[:, :num_nodes - 1] + layer_costs[:, ::2]) < sens) * prev_act[:, :num_nodes - 1]
            r_cs_res = ((V_2 - V_1[:, 1:num_nodes] + layer_costs[:, 1::2]) < sens) * prev_act[:, 1:num_nodes]
            prev_act = torch.zeros(V_2.shape)
            prev_act += l_cs_res
            prev_act += r_cs_res
        cs = torch.zeros(layer_costs.shape)
        cs[:, ::2] = l_cs_res
        cs[:, 1::2] = r_cs_res
        sol[:, starting_ind_c - num_arcs: starting_ind_c] = cs

        starting_ind = starting_ind - num_nodes
        starting_ind_c = starting_ind_c - num_arcs
    # Dimension (samples, num edges)
    obj = torch.sum(sol * costs, axis=1)
    # Dimension (samples, 1)
    return sol.to(torch.float32), obj.reshape(-1,1).to(torch.float32)

# Verify Previous Results

# Compare Input Data

### Shared Inputs to both old and new data

In [41]:
torch.manual_seed(105)
indices_arr = torch.randperm(100000)
indices_arr_test = torch.randperm(100000)

sim = 0
n_arr = [200, 400, 800, 1600]
ep_arr = ['unif', 'normal']
trials = 100

exp_arr = []
for n in n_arr:
    for ep in ep_arr:
        for t in range(trials):
            exp_arr.append([n, ep, t])

# setup
exp = exp_arr[0]
ep_type = exp[1]
trial = exp[2]

# generate data
grid = (5, 5)  # grid size
num_data = exp[0]  # number of training data
num_feat = 5  # size of feature
deg = 6  # polynomial degree
e = .3  # noise width

print(num_data, ep_type, trial)

200 unif 0


### New Input Data

In [87]:
import decision_learning.data.shortest_path_grid
importlib.reload(decision_learning.data.shortest_path_grid)
from decision_learning.data.shortest_path_grid import genData

In [88]:
# path planting for shortest path example
planted_good_pwl_params = {'slope0':0, 
                    'int0':2,
                    'slope1':0, 
                    'int1':2}
planted_bad_pwl_params = {'slope0':4, 
                    'int0':0,
                    'slope1':0, 
                    'int1':2.2}

plant_edge = True

In [432]:
generated_data = genData(num_data=num_data+200,
        num_features=num_feat, 
        grid=grid, 
        deg=deg, 
        noise_type=ep_type,
        noise_width=e,
        seed=indices_arr[trial],     
        plant_edges=plant_edge,
        planted_good_pwl_params=planted_good_pwl_params,
        planted_bad_pwl_params=planted_bad_pwl_params)
sol, obj = shortest_path_solver(costs=generated_data['cost'], size=5)
final_data = {'X':generated_data['feat'],
              'true_cost':generated_data['cost'],
              'true_sol':sol,
              'true_obj':obj}

# Splitting each input in the same way
train_dict = {}
val_dict = {}

for key, value in final_data.items():
    train_data, val_data = train_test_split(value, test_size=200, random_state=42)
    train_dict[key] = train_data
    val_dict[key] = val_data
    
# test data
generated_data_test = genData(num_data=10000,
        num_features=num_feat, 
        grid=grid, 
        deg=deg, 
        noise_type=ep_type,
        noise_width=e,
        seed=indices_arr_test[trial],     
        plant_edges=plant_edge,
        planted_good_pwl_params=planted_good_pwl_params,
        planted_bad_pwl_params=planted_bad_pwl_params)
sol_test, obj_test = shortest_path_solver(costs=generated_data_test['cost_true'], size=5)
final_data_test = {'X':generated_data_test['feat'],
              'true_cost':generated_data_test['cost_true'],
              'true_sol':sol_test,
              'true_obj':obj_test}

2024-11-13 16:23:53,068 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 10 11 12 13 14 17 18 19 20 21 22 25 26 27 28 29 32 33 34 37]
2024-11-13 16:23:53,068 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 10 11 12 13 14 17 18 19 20 21 22 25 26 27 28 29 32 33 34 37]
2024-11-13 16:23:53,069 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.0
2024-11-13 16:23:53,069 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.0
2024-11-13 16:23:53,069 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.55
2024-11-13 16:23:53,069 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.55
2024-11-13 16:23:53,096 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 

In [431]:
generated_data_test.keys()

dict_keys(['feat', 'cost_noplant', 'cost_true', 'cost', 'epsilon'])

### Old Input Data

In [234]:
import sys
sys.path.append('/home1/yongpeng/decision-focused-learning/experiments/shortest_path_grid_exp/')
import sp_grid_mike_neurips
importlib.reload(sp_grid_mike_neurips)
import sp_grid_mike_neurips

In [131]:
feat, cost_true, cost, eps = sp_grid_mike_neurips.genData(num_data + 200, 
                                                     num_feat, 
                                                     grid, 
                                                     ep_type, 
                                                     deg, 
                                                     e, 
                                                     seed=indices_arr[trial])
x_train, x_val, c_train, c_val = train_test_split(feat, cost, test_size=200, random_state=42)
x_test, c_test, c_hat_test, eps_test = sp_grid_mike_neurips.genData(10000, 
                                                          num_feat, 
                                                          grid, 
                                                          ep_type, 
                                                          deg, 
                                                          e, 
                                                          seed=indices_arr_test[trial])

# train
sol_tr, obj_tr = shortest_path_solver(costs=c_train, size=5)
train_dict_old = {'X':x_train[:,:-1],
              'true_cost':c_train,
              'true_sol':sol_tr,
              'true_obj':obj_tr}
# val
sol_v, obj_v = shortest_path_solver(costs=c_val, size=5)
val_dict_old = {'X':x_val[:,:-1],
              'true_cost':c_val,
              'true_sol':sol_v,
              'true_obj':obj_v}

# test
sol_te, obj_te = shortest_path_solver(costs=c_hat_test, size=5)
final_data_te = {'X':x_test[:,:-1],
              'true_cost':c_hat_test,
              'true_sol':sol_te,
              'true_obj':obj_te}

### Compare the old and new data inputs

#### Costs before noise

In [93]:
(torch.tensor(generated_data['cost_true'], dtype=torch.float32) == cost_true).all()

tensor(True)

#### Costs After Noise

In [94]:
(torch.tensor(generated_data['cost'], dtype=torch.float32) == cost).all()

tensor(True)

#### Training Data

In [113]:
for k in train_dict.keys():
    print(k)
    print(torch.allclose(torch.tensor(train_dict[k], dtype=torch.float32),
                   train_dict_old[k]))
                   

X
True
true_cost
True
true_sol
True
true_obj
True


/tmp/SLURM_27423203/ipykernel_37376/1802200100.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.allclose(torch.tensor(train_dict[k], dtype=torch.float32),


#### Validation Data

In [116]:
for k in val_dict.keys():
    print(k)
    print(torch.allclose(torch.tensor(val_dict[k], dtype=torch.float32),
                   val_dict_old[k]))

X
True
true_cost
True
true_sol
True
true_obj
True


/tmp/SLURM_27423203/ipykernel_37376/2673537216.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.allclose(torch.tensor(val_dict[k], dtype=torch.float32),


#### Test Data

In [132]:
for k in final_data_test.keys():
    print(k)
    print(torch.allclose(torch.tensor(final_data_test[k], dtype=torch.float32),
                   final_data_te[k]))

X
True
true_cost
True
true_sol
True
true_obj
True


/tmp/SLURM_27423203/ipykernel_37376/4035419391.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.allclose(torch.tensor(final_data_test[k], dtype=torch.float32),


# Data All the Same!

# Loss Function Difference?

In [291]:
predmodel = LinearRegression(input_dim=feat.shape[1],
                 output_dim=train_dict['true_cost'].shape[1])
optimizer = torch.optim.Adam(pred_model.parameters(), lr=0.01)

#### Loss Calc

New Loss Function

In [292]:
new_loss_fn = SPOPlus(optmodel=optmodel)

In [293]:
cp = predmodel(train_dict_old['X'])
new_loss = new_loss_fn(cp,
            true_cost=train_dict_old['true_cost'],
            true_sol=train_dict_old['true_sol'], 
            true_obj=train_dict_old['true_obj'])
new_loss

tensor(10.9612, grad_fn=<MeanBackward0>)

Gradient

In [294]:
new_loss.backward()

In [295]:
# Check gradients

print("Gradients of the model's parameters:")
for name, param in predmodel.named_parameters():
    print(f"{name} gradient:\n{param.grad[0]}")

Gradients of the model's parameters:
linear.weight gradient:
tensor([-0.1378,  0.3801, -0.2576,  0.1089,  0.1560, -1.0474, -0.5900])
linear.bias gradient:
-0.5899999737739563


In [297]:
# Reset gradients
for param in predmodel.parameters():
    if param.grad is not None:
        param.grad.zero_()

Old Loss

In [334]:
import sp_grid_mike_neurips
importlib.reload(sp_grid_mike_neurips)
from sp_grid_mike_neurips import SPOPlus2, regret_func, trainModel, regret_func

In [299]:
optmodel_old = sp_grid_mike_neurips.shortestPathModel()
old_loss_fn = SPOPlus2(optmodel_old)

cp = predmodel(train_dict_old['X'])
old_loss = old_loss_fn(cp,
            true_cost=train_dict_old['true_cost'],
            true_sol=train_dict_old['true_sol'], 
            true_obj=train_dict_old['true_obj'])
old_loss

Num of cores: 1


tensor(10.9612, grad_fn=<MeanBackward0>)

In [300]:
old_loss.backward()

In [301]:
# Check gradients
print("Gradients of the model's parameters:")
for name, param in predmodel.named_parameters():
    print(f"{name} gradient:\n{param.grad[0]}")

Gradients of the model's parameters:
linear.weight gradient:
tensor([-0.1378,  0.3801, -0.2576,  0.1089,  0.1560, -1.0474, -0.5900])
linear.bias gradient:
-0.5899999737739563


In [286]:
# Reset gradients
for param in predmodel.parameters():
    if param.grad is not None:
        param.grad.zero_()

Gradients also the same

In [313]:
predmodel = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])

Baby New Training Loop

In [433]:
new_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])
new_model.linear = copy.deepcopy(predmodel.linear)

optmodel = partial(shortest_path_solver,size=5)
loss_fn = SPOPlus(optmodel=optmodel)

preset_params = {'optmodel': optmodel, 'minimize': True}
val_metric = partial(decision_regret, **preset_params)

optimizer = torch.optim.Adam(new_model.parameters(), lr=0.01)
train_dataset, train_loader = init_loss_data_pretraining(train_dict, {'batch_size':200, 'shuffle':True})  # training data        
val_dataset, val_loader = init_loss_data_pretraining(val_dict, {'batch_size':200, 'shuffle':True})  # validation data
    

In [434]:
metrics = []
for epoch in range(100):
    epoch_losses = []
    new_model.train() # beginning of epoch, set model to training mode
    for batch_idx, batch in enumerate(tqdm(train_loader)):    
                
        pred = new_model(batch['X'])
        
        batch = filter_kwargs(loss_fn.forward, batch) # filter out only valid arguments for the loss function                         
        loss = loss_fn(pred, **batch) # we assume the first argument of the loss function is the prediction, while the rest can be passed as kwargs
        
        # standard backwards pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        epoch_losses.append(loss.item())        
    
    print(new_model.linear.weight[0])
    new_model.eval()
    all_preds = []
    with torch.no_grad():
        for batch_idx, batch in enumerate(tqdm(val_loader)):                    
            pred = new_model(batch['X'])                    
            all_preds.append(pred)
    all_preds = torch.cat(all_preds, dim=0)
    
    val_data_dict = filter_kwargs(val_metric, val_dict) # filter out only valid arguments for the val metric    
    val_loss = val_metric(all_preds, **val_data_dict)

    cur_metric = {'epoch': epoch, 
                    'train_loss': np.mean(epoch_losses), 
                    'val_metric': val_loss}
    metrics.append(cur_metric)
    
    print(f'epoch: {epoch}, train_loss: {np.mean(epoch_losses)}, val_metric: {val_loss}')
metrics = pd.DataFrame(metrics)

100%|██████████| 1/1 [00:00<00:00, 250.26it/s]


tensor([-0.3795,  0.1344, -0.3751, -0.3201, -0.0209,  0.3107],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 665.02it/s]


epoch: 0, train_loss: 17.493484497070312, val_metric: 0.5201238330848681


100%|██████████| 1/1 [00:00<00:00, 328.01it/s]


tensor([-0.3714,  0.1244, -0.3651, -0.3298, -0.0309,  0.3202],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 212.00it/s]


epoch: 1, train_loss: 16.7802677154541, val_metric: 0.4958449865293985


100%|██████████| 1/1 [00:00<00:00, 327.88it/s]


tensor([-0.3660,  0.1144, -0.3551, -0.3358, -0.0407,  0.3299],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 697.08it/s]


epoch: 2, train_loss: 16.084394454956055, val_metric: 0.504316426469192


100%|██████████| 1/1 [00:00<00:00, 333.52it/s]


tensor([-0.3653,  0.1044, -0.3451, -0.3390, -0.0503,  0.3397],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 543.94it/s]


epoch: 3, train_loss: 15.414484977722168, val_metric: 0.44975737804717386


100%|██████████| 1/1 [00:00<00:00, 172.73it/s]


tensor([-0.3689,  0.0945, -0.3351, -0.3377, -0.0599,  0.3494],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 690.31it/s]


epoch: 4, train_loss: 14.766685485839844, val_metric: 0.4425716603939225


100%|██████████| 1/1 [00:00<00:00, 333.01it/s]


tensor([-0.3657,  0.0845, -0.3251, -0.3331, -0.0693,  0.3591],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 697.08it/s]


epoch: 5, train_loss: 14.13941764831543, val_metric: 0.4411389452555182


100%|██████████| 1/1 [00:00<00:00, 332.72it/s]


tensor([-0.3603,  0.0746, -0.3152, -0.3279, -0.0785,  0.3688],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 693.96it/s]


epoch: 6, train_loss: 13.531818389892578, val_metric: 0.4276200219730913


100%|██████████| 1/1 [00:00<00:00, 332.62it/s]


tensor([-0.3534,  0.0647, -0.3054, -0.3217, -0.0872,  0.3785],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 675.96it/s]


epoch: 7, train_loss: 12.951427459716797, val_metric: 0.40223044905155625


100%|██████████| 1/1 [00:00<00:00, 332.35it/s]


tensor([-0.3456,  0.0549, -0.2956, -0.3145, -0.0955,  0.3877],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 681.78it/s]


epoch: 8, train_loss: 12.397736549377441, val_metric: 0.39758152101106065


100%|██████████| 1/1 [00:00<00:00, 332.70it/s]


tensor([-0.3371,  0.0452, -0.2859, -0.3077, -0.1031,  0.3970],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 650.18it/s]


epoch: 9, train_loss: 11.860346794128418, val_metric: 0.3653961336275114


100%|██████████| 1/1 [00:00<00:00, 337.60it/s]


tensor([-0.3281,  0.0356, -0.2763, -0.3022, -0.1101,  0.4065],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 566.57it/s]


epoch: 10, train_loss: 11.4478120803833, val_metric: 0.3371268497945089


100%|██████████| 1/1 [00:00<00:00, 329.17it/s]


tensor([-0.3190,  0.0261, -0.2670, -0.3014, -0.1164,  0.4163],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 721.41it/s]


epoch: 11, train_loss: 10.870155334472656, val_metric: 0.33167383364094655


100%|██████████| 1/1 [00:00<00:00, 337.08it/s]


tensor([-0.3103,  0.0167, -0.2578, -0.3032, -0.1221,  0.4263],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 722.16it/s]


epoch: 12, train_loss: 10.404491424560547, val_metric: 0.27706080255924936


100%|██████████| 1/1 [00:00<00:00, 338.96it/s]


tensor([-0.3025,  0.0073, -0.2489, -0.3078, -0.1270,  0.4365],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 712.83it/s]


epoch: 13, train_loss: 9.957537651062012, val_metric: 0.2579039126235752


100%|██████████| 1/1 [00:00<00:00, 338.41it/s]


tensor([-0.2953, -0.0020, -0.2405, -0.3136, -0.1315,  0.4469],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 724.15it/s]


epoch: 14, train_loss: 9.53393840789795, val_metric: 0.2534060941651285


100%|██████████| 1/1 [00:00<00:00, 339.56it/s]


tensor([-0.2895, -0.0110, -0.2322, -0.3204, -0.1355,  0.4575],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 711.02it/s]


epoch: 15, train_loss: 9.12744426727295, val_metric: 0.2366724697741817


100%|██████████| 1/1 [00:00<00:00, 338.11it/s]


tensor([-0.2854, -0.0197, -0.2242, -0.3272, -0.1389,  0.4683],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 713.80it/s]


epoch: 16, train_loss: 8.753935813903809, val_metric: 0.2286809894057537


100%|██████████| 1/1 [00:00<00:00, 337.71it/s]


tensor([-0.2832, -0.0281, -0.2166, -0.3344, -0.1418,  0.4787],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 717.34it/s]


epoch: 17, train_loss: 8.40645980834961, val_metric: 0.21928030810354687


100%|██████████| 1/1 [00:00<00:00, 339.37it/s]


tensor([-0.2829, -0.0361, -0.2093, -0.3420, -0.1442,  0.4890],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 728.18it/s]


epoch: 18, train_loss: 8.08495807647705, val_metric: 0.19484784006286368


100%|██████████| 1/1 [00:00<00:00, 339.84it/s]


tensor([-0.2843, -0.0439, -0.2025, -0.3488, -0.1457,  0.4991],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 711.02it/s]


epoch: 19, train_loss: 7.781777858734131, val_metric: 0.20823235326761463


100%|██████████| 1/1 [00:00<00:00, 339.78it/s]


tensor([-0.2878, -0.0514, -0.1961, -0.3539, -0.1462,  0.5092],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 718.08it/s]


epoch: 20, train_loss: 7.506954193115234, val_metric: 0.2231086345935038


100%|██████████| 1/1 [00:00<00:00, 338.96it/s]


tensor([-0.2927, -0.0583, -0.1902, -0.3565, -0.1460,  0.5193],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 712.23it/s]


epoch: 21, train_loss: 7.251377582550049, val_metric: 0.22077258790866308


100%|██████████| 1/1 [00:00<00:00, 338.80it/s]


tensor([-0.2989, -0.0648, -0.1847, -0.3571, -0.1452,  0.5293],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 712.47it/s]


epoch: 22, train_loss: 7.011843204498291, val_metric: 0.20793755352119786


100%|██████████| 1/1 [00:00<00:00, 339.29it/s]


tensor([-0.3063, -0.0710, -0.1796, -0.3569, -0.1439,  0.5385],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 716.24it/s]


epoch: 23, train_loss: 6.787109851837158, val_metric: 0.218781183641369


100%|██████████| 1/1 [00:00<00:00, 331.93it/s]


tensor([-0.3146, -0.0768, -0.1750, -0.3557, -0.1420,  0.5473],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 717.83it/s]


epoch: 24, train_loss: 6.573312759399414, val_metric: 0.2110014939231084


100%|██████████| 1/1 [00:00<00:00, 337.46it/s]


tensor([-0.3235, -0.0822, -0.1709, -0.3537, -0.1395,  0.5555],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 701.51it/s]


epoch: 25, train_loss: 6.380495071411133, val_metric: 0.21757519102194467


100%|██████████| 1/1 [00:00<00:00, 339.54it/s]


tensor([-0.3329, -0.0872, -0.1676, -0.3508, -0.1367,  0.5628],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 713.44it/s]


epoch: 26, train_loss: 6.205470561981201, val_metric: 0.2320772918097389


100%|██████████| 1/1 [00:00<00:00, 334.10it/s]


tensor([-0.3419, -0.0918, -0.1649, -0.3470, -0.1336,  0.5685],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 713.92it/s]


epoch: 27, train_loss: 6.049722194671631, val_metric: 0.22663125316496746


100%|██████████| 1/1 [00:00<00:00, 331.75it/s]


tensor([-0.3500, -0.0958, -0.1628, -0.3423, -0.1304,  0.5732],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 716.00it/s]


epoch: 28, train_loss: 5.910831928253174, val_metric: 0.22604909634817755


100%|██████████| 1/1 [00:00<00:00, 333.46it/s]


tensor([-0.3570, -0.0994, -0.1613, -0.3380, -0.1268,  0.5767],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 705.04it/s]


epoch: 29, train_loss: 5.795680999755859, val_metric: 0.21721808212202487


100%|██████████| 1/1 [00:00<00:00, 319.57it/s]


tensor([-0.3630, -0.1025, -0.1604, -0.3334, -0.1230,  0.5790],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 699.87it/s]


epoch: 30, train_loss: 5.688831329345703, val_metric: 0.23594827413677105


100%|██████████| 1/1 [00:00<00:00, 330.29it/s]


tensor([-0.3674, -0.1051, -0.1600, -0.3288, -0.1191,  0.5804],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 704.69it/s]


epoch: 31, train_loss: 5.5939812660217285, val_metric: 0.23386451091144772


100%|██████████| 1/1 [00:00<00:00, 330.36it/s]


tensor([-0.3712, -0.1072, -0.1601, -0.3246, -0.1155,  0.5818],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 708.26it/s]


epoch: 32, train_loss: 5.511480808258057, val_metric: 0.23358308472354686


100%|██████████| 1/1 [00:00<00:00, 334.39it/s]


tensor([-0.3750, -0.1088, -0.1604, -0.3213, -0.1123,  0.5835],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 692.82it/s]


epoch: 33, train_loss: 5.441272735595703, val_metric: 0.24619886252643844


100%|██████████| 1/1 [00:00<00:00, 335.30it/s]


tensor([-0.3787, -0.1102, -0.1608, -0.3193, -0.1095,  0.5858],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 709.94it/s]

epoch: 34, train_loss: 5.375828266143799, val_metric: 0.23094849369590487

100%|██████████| 1/1 [00:00<00:00, 338.77it/s]


tensor([-0.3821, -0.1113, -0.1613, -0.3190, -0.1069,  0.5887],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 722.04it/s]


epoch: 35, train_loss: 5.315378189086914, val_metric: 0.22687560552282585


100%|██████████| 1/1 [00:00<00:00, 341.69it/s]


tensor([-0.3855, -0.1122, -0.1618, -0.3195, -0.1043,  0.5924],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 719.19it/s]

epoch: 36, train_loss: 5.257638931274414, val_metric: 0.2266222056619019

100%|██████████| 1/1 [00:00<00:00, 338.28it/s]

tensor([-0.3878, -0.1129, -0.1622, -0.3208, -0.1018,  0.5974],
       grad_fn=<SelectBackward0>)

100%|██████████| 1/1 [00:00<00:00, 696.15it/s]


epoch: 37, train_loss: 5.319481372833252, val_metric: 0.2290633103707714


100%|██████████| 1/1 [00:00<00:00, 337.65it/s]


tensor([-0.3886, -0.1136, -0.1623, -0.3199, -0.0995,  0.6034],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 702.09it/s]


epoch: 38, train_loss: 5.158652305603027, val_metric: 0.22498581704189036


100%|██████████| 1/1 [00:00<00:00, 337.62it/s]


tensor([-0.3879, -0.1143, -0.1622, -0.3173, -0.0975,  0.6104],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 689.40it/s]


epoch: 39, train_loss: 5.114628791809082, val_metric: 0.23095500603744307


100%|██████████| 1/1 [00:00<00:00, 338.63it/s]


tensor([-0.3858, -0.1150, -0.1617, -0.3130, -0.0957,  0.6184],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 697.89it/s]


epoch: 40, train_loss: 5.162067890167236, val_metric: 0.21809392228382504


100%|██████████| 1/1 [00:00<00:00, 332.38it/s]


tensor([-0.3831, -0.1155, -0.1615, -0.3089, -0.0941,  0.6268],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 703.62it/s]


epoch: 41, train_loss: 5.0354905128479, val_metric: 0.2200976302249538


100%|██████████| 1/1 [00:00<00:00, 333.44it/s]


tensor([-0.3807, -0.1160, -0.1615, -0.3066, -0.0930,  0.6354],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 712.47it/s]


epoch: 42, train_loss: 4.998876094818115, val_metric: 0.22841149475788536


100%|██████████| 1/1 [00:00<00:00, 332.38it/s]


tensor([-0.3787, -0.1163, -0.1617, -0.3058, -0.0925,  0.6437],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 706.71it/s]


epoch: 43, train_loss: 4.966946601867676, val_metric: 0.23590978154660777


100%|██████████| 1/1 [00:00<00:00, 332.67it/s]


tensor([-0.3770, -0.1165, -0.1622, -0.3063, -0.0923,  0.6519],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 711.99it/s]


epoch: 44, train_loss: 4.935837268829346, val_metric: 0.23088267252964376


100%|██████████| 1/1 [00:00<00:00, 334.79it/s]


tensor([-0.3759, -0.1166, -0.1628, -0.3072, -0.0929,  0.6599],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 703.86it/s]


epoch: 45, train_loss: 4.9069318771362305, val_metric: 0.23649975317324354


100%|██████████| 1/1 [00:00<00:00, 329.25it/s]


tensor([-0.3755, -0.1166, -0.1636, -0.3082, -0.0939,  0.6678],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 701.51it/s]


epoch: 46, train_loss: 4.880943775177002, val_metric: 0.24094731031003286


100%|██████████| 1/1 [00:00<00:00, 331.23it/s]


tensor([-0.3756, -0.1168, -0.1641, -0.3077, -0.0951,  0.6758],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 699.17it/s]


epoch: 47, train_loss: 4.855621814727783, val_metric: 0.22431144081724697


100%|██████████| 1/1 [00:00<00:00, 331.54it/s]


tensor([-0.3762, -0.1169, -0.1641, -0.3054, -0.0965,  0.6840],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 698.35it/s]


epoch: 48, train_loss: 4.830745220184326, val_metric: 0.2308353882784039


100%|██████████| 1/1 [00:00<00:00, 331.30it/s]


tensor([-0.3769, -0.1171, -0.1641, -0.3032, -0.0984,  0.6919],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 706.59it/s]


epoch: 49, train_loss: 4.805846214294434, val_metric: 0.23409504780190005


100%|██████████| 1/1 [00:00<00:00, 330.44it/s]


tensor([-0.3774, -0.1170, -0.1641, -0.3017, -0.1008,  0.6996],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 701.15it/s]


epoch: 50, train_loss: 4.780776023864746, val_metric: 0.24259777023943946


100%|██████████| 1/1 [00:00<00:00, 328.94it/s]


tensor([-0.3778, -0.1169, -0.1640, -0.3008, -0.1038,  0.7068],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 696.61it/s]


epoch: 51, train_loss: 4.75584077835083, val_metric: 0.2455132059959164


100%|██████████| 1/1 [00:00<00:00, 330.96it/s]


tensor([-0.3781, -0.1167, -0.1640, -0.3004, -0.1073,  0.7136],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 701.39it/s]


epoch: 52, train_loss: 4.7312116622924805, val_metric: 0.2310489930808569


100%|██████████| 1/1 [00:00<00:00, 331.25it/s]


tensor([-0.3789, -0.1165, -0.1638, -0.3002, -0.1110,  0.7198],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 699.52it/s]


epoch: 53, train_loss: 4.706007480621338, val_metric: 0.24378359785845802


100%|██████████| 1/1 [00:00<00:00, 330.60it/s]


tensor([-0.3797, -0.1163, -0.1636, -0.3011, -0.1149,  0.7257],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 703.62it/s]


epoch: 54, train_loss: 4.681149482727051, val_metric: 0.24765923185801747


100%|██████████| 1/1 [00:00<00:00, 331.43it/s]


tensor([-0.3805, -0.1160, -0.1633, -0.3027, -0.1184,  0.7311],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 703.03it/s]


epoch: 55, train_loss: 4.658987045288086, val_metric: 0.24909543575081722


100%|██████████| 1/1 [00:00<00:00, 332.17it/s]


tensor([-0.3818, -0.1157, -0.1630, -0.3052, -0.1214,  0.7362],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 702.56it/s]


epoch: 56, train_loss: 4.6378068923950195, val_metric: 0.24672889735256012


100%|██████████| 1/1 [00:00<00:00, 330.39it/s]


tensor([-0.3831, -0.1155, -0.1625, -0.3089, -0.1235,  0.7409],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 685.46it/s]


epoch: 57, train_loss: 4.619064807891846, val_metric: 0.24787783720843728


100%|██████████| 1/1 [00:00<00:00,  7.29it/s]


tensor([-0.3840, -0.1153, -0.1613, -0.3117, -0.1249,  0.7458],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 617.81it/s]


epoch: 58, train_loss: 4.601837635040283, val_metric: 0.23873888226097825


100%|██████████| 1/1 [00:00<00:00, 316.50it/s]


tensor([-0.3844, -0.1151, -0.1598, -0.3133, -0.1254,  0.7514],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 670.02it/s]


epoch: 59, train_loss: 4.586855411529541, val_metric: 0.2511411250365047


100%|██████████| 1/1 [00:00<00:00, 325.11it/s]


tensor([-0.3848, -0.1150, -0.1584, -0.3150, -0.1254,  0.7570],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 688.15it/s]


epoch: 60, train_loss: 4.571585178375244, val_metric: 0.2104731104407339


100%|██████████| 1/1 [00:00<00:00, 334.45it/s]


tensor([-0.3844, -0.1149, -0.1572, -0.3167, -0.1248,  0.7626],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 661.46it/s]


epoch: 61, train_loss: 4.556169033050537, val_metric: 0.22707211542874106


100%|██████████| 1/1 [00:00<00:00, 331.41it/s]


tensor([-0.3836, -0.1149, -0.1563, -0.3182, -0.1238,  0.7681],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 674.22it/s]


epoch: 62, train_loss: 4.540851593017578, val_metric: 0.2250647559246784


100%|██████████| 1/1 [00:00<00:00, 332.25it/s]


tensor([-0.3821, -0.1149, -0.1558, -0.3198, -0.1226,  0.7737],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 686.92it/s]


epoch: 63, train_loss: 4.525737762451172, val_metric: 0.22658380610518913


100%|██████████| 1/1 [00:00<00:00, 332.14it/s]


tensor([-0.3804, -0.1150, -0.1556, -0.3211, -0.1210,  0.7794],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 678.47it/s]


epoch: 64, train_loss: 4.510251045227051, val_metric: 0.226804202349532


100%|██████████| 1/1 [00:00<00:00, 327.94it/s]


tensor([-0.3787, -0.1151, -0.1558, -0.3219, -0.1192,  0.7851],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 700.10it/s]


epoch: 65, train_loss: 4.495913028717041, val_metric: 0.23643325751446598


100%|██████████| 1/1 [00:00<00:00, 330.60it/s]


tensor([-0.3770, -0.1152, -0.1564, -0.3223, -0.1172,  0.7909],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 699.98it/s]


epoch: 66, train_loss: 4.482025146484375, val_metric: 0.21950868196627402


100%|██████████| 1/1 [00:00<00:00, 334.79it/s]


tensor([-0.3753, -0.1151, -0.1570, -0.3233, -0.1155,  0.7968],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 625.18it/s]


epoch: 67, train_loss: 4.469078063964844, val_metric: 0.23724278808438967


100%|██████████| 1/1 [00:00<00:00, 330.49it/s]


tensor([-0.3733, -0.1149, -0.1577, -0.3251, -0.1142,  0.8026],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 698.35it/s]


epoch: 68, train_loss: 4.45615816116333, val_metric: 0.21319415280229553


100%|██████████| 1/1 [00:00<00:00, 329.66it/s]


tensor([-0.3711, -0.1145, -0.1584, -0.3271, -0.1135,  0.8082],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 675.63it/s]


epoch: 69, train_loss: 4.443439483642578, val_metric: 0.2215703264887301


100%|██████████| 1/1 [00:00<00:00, 326.99it/s]


tensor([-0.3686, -0.1139, -0.1592, -0.3292, -0.1134,  0.8137],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 746.18it/s]


epoch: 70, train_loss: 4.430868148803711, val_metric: 0.22846991976482808


100%|██████████| 1/1 [00:00<00:00, 345.38it/s]


tensor([-0.3662, -0.1131, -0.1599, -0.3310, -0.1139,  0.8189],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 747.51it/s]


epoch: 71, train_loss: 4.418442249298096, val_metric: 0.22632952242648502


100%|██████████| 1/1 [00:00<00:00, 296.90it/s]


tensor([-0.3651, -0.1121, -0.1607, -0.3319, -0.1148,  0.8238],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 554.95it/s]


epoch: 72, train_loss: 4.407078266143799, val_metric: 0.21793062531975466


100%|██████████| 1/1 [00:00<00:00, 340.94it/s]


tensor([-0.3650, -0.1110, -0.1615, -0.3315, -0.1160,  0.8284],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 708.86it/s]


epoch: 73, train_loss: 4.396327018737793, val_metric: 0.21226193436946464


100%|██████████| 1/1 [00:00<00:00, 337.16it/s]


tensor([-0.3663, -0.1098, -0.1623, -0.3293, -0.1172,  0.8329],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 722.41it/s]


epoch: 74, train_loss: 4.385149955749512, val_metric: 0.21553243228994937


100%|██████████| 1/1 [00:00<00:00, 337.19it/s]


tensor([-0.3685, -0.1085, -0.1629, -0.3271, -0.1183,  0.8369],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 723.65it/s]


epoch: 75, train_loss: 4.374324321746826, val_metric: 0.21207328579012052


100%|██████████| 1/1 [00:00<00:00, 334.05it/s]


tensor([-0.3702, -0.1072, -0.1634, -0.3273, -0.1198,  0.8412],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 669.80it/s]


epoch: 76, train_loss: 4.435861587524414, val_metric: 0.2449051626215121


100%|██████████| 1/1 [00:00<00:00, 328.24it/s]


tensor([-0.3715, -0.1060, -0.1636, -0.3289, -0.1211,  0.8453],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 715.51it/s]


epoch: 77, train_loss: 4.3557047843933105, val_metric: 0.2156160926203526


100%|██████████| 1/1 [00:00<00:00, 336.00it/s]


tensor([-0.3726, -0.1051, -0.1635, -0.3317, -0.1220,  0.8493],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 716.12it/s]


epoch: 78, train_loss: 4.346749782562256, val_metric: 0.23049497888285705


100%|██████████| 1/1 [00:00<00:00, 336.41it/s]


tensor([-0.3733, -0.1041, -0.1630, -0.3346, -0.1226,  0.8537],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 696.84it/s]


epoch: 79, train_loss: 4.337762832641602, val_metric: 0.21344545941058218


100%|██████████| 1/1 [00:00<00:00, 333.70it/s]


tensor([-0.3733, -0.1032, -0.1625, -0.3366, -0.1232,  0.8582],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 712.59it/s]


epoch: 80, train_loss: 4.328524112701416, val_metric: 0.20861458119918178


100%|██████████| 1/1 [00:00<00:00, 327.88it/s]


tensor([-0.3727, -0.1021, -0.1619, -0.3377, -0.1238,  0.8629],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 715.39it/s]


epoch: 81, train_loss: 4.3193440437316895, val_metric: 0.2261120102191091


100%|██████████| 1/1 [00:00<00:00, 330.60it/s]

tensor([-0.3725, -0.1012, -0.1612, -0.3378, -0.1243,  0.8676],
       grad_fn=<SelectBackward0>)

100%|██████████| 1/1 [00:00<00:00, 715.51it/s]


epoch: 82, train_loss: 4.310288429260254, val_metric: 0.2516409007328364


100%|██████████| 1/1 [00:00<00:00, 329.79it/s]


tensor([-0.3723, -0.1002, -0.1605, -0.3380, -0.1248,  0.8720],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 698.70it/s]


epoch: 83, train_loss: 4.301353931427002, val_metric: 0.24144376006050755


100%|██████████| 1/1 [00:00<00:00, 336.57it/s]


tensor([-0.3721, -0.0992, -0.1599, -0.3385, -0.1255,  0.8763],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 711.74it/s]


epoch: 84, train_loss: 4.292416095733643, val_metric: 0.20598652577144064


100%|██████████| 1/1 [00:00<00:00, 328.37it/s]


tensor([-0.3725, -0.0982, -0.1592, -0.3389, -0.1261,  0.8805],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 702.21it/s]


epoch: 85, train_loss: 4.284042835235596, val_metric: 0.21305136971407046


100%|██████████| 1/1 [00:00<00:00, 333.81it/s]


tensor([-0.3738, -0.0974, -0.1586, -0.3393, -0.1267,  0.8847],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 722.41it/s]


epoch: 86, train_loss: 4.3080925941467285, val_metric: 0.23077517237753817


100%|██████████| 1/1 [00:00<00:00, 332.46it/s]


tensor([-0.3756, -0.0966, -0.1581, -0.3395, -0.1273,  0.8889],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 716.00it/s]


epoch: 87, train_loss: 4.2685699462890625, val_metric: 0.21765587428193045


100%|██████████| 1/1 [00:00<00:00, 334.39it/s]


tensor([-0.3772, -0.0959, -0.1576, -0.3394, -0.1277,  0.8931],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 741.04it/s]


epoch: 88, train_loss: 4.260875701904297, val_metric: 0.19987634458158585


100%|██████████| 1/1 [00:00<00:00, 292.18it/s]


tensor([-0.3778, -0.0952, -0.1571, -0.3402, -0.1281,  0.8973],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 704.21it/s]


epoch: 89, train_loss: 4.253096103668213, val_metric: 0.22336089479465857


100%|██████████| 1/1 [00:00<00:00, 342.36it/s]


tensor([-0.3797, -0.0944, -0.1568, -0.3405, -0.1285,  0.9015],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 705.99it/s]


epoch: 90, train_loss: 4.2456536293029785, val_metric: 0.222685378910246


100%|██████████| 1/1 [00:00<00:00, 334.18it/s]


tensor([-0.3817, -0.0934, -0.1567, -0.3412, -0.1288,  0.9052],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 704.21it/s]


epoch: 91, train_loss: 4.238111972808838, val_metric: 0.21472132015136638


100%|██████████| 1/1 [00:00<00:00, 334.71it/s]


tensor([-0.3835, -0.0925, -0.1568, -0.3418, -0.1287,  0.9084],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 543.66it/s]


epoch: 92, train_loss: 4.231278419494629, val_metric: 0.20921771705906977


100%|██████████| 1/1 [00:00<00:00, 338.77it/s]


tensor([-0.3843, -0.0917, -0.1568, -0.3428, -0.1285,  0.9114],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 724.78it/s]


epoch: 93, train_loss: 4.2244062423706055, val_metric: 0.21965923334761964


100%|██████████| 1/1 [00:00<00:00, 333.70it/s]


tensor([-0.3842, -0.0911, -0.1569, -0.3430, -0.1280,  0.9144],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 705.64it/s]


epoch: 94, train_loss: 4.217450141906738, val_metric: 0.2379146989225936


100%|██████████| 1/1 [00:00<00:00, 338.03it/s]


tensor([-0.3839, -0.0905, -0.1569, -0.3431, -0.1275,  0.9172],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 707.30it/s]


epoch: 95, train_loss: 4.210359573364258, val_metric: 0.21119500350024353


100%|██████████| 1/1 [00:00<00:00, 336.86it/s]


tensor([-0.3839, -0.0901, -0.1570, -0.3426, -0.1266,  0.9198],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 723.65it/s]


epoch: 96, train_loss: 4.203843593597412, val_metric: 0.2363306881352393


100%|██████████| 1/1 [00:00<00:00, 336.19it/s]


tensor([-0.3838, -0.0895, -0.1570, -0.3423, -0.1260,  0.9225],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 724.28it/s]


epoch: 97, train_loss: 4.197504043579102, val_metric: 0.1993713590120236


100%|██████████| 1/1 [00:00<00:00, 334.79it/s]


tensor([-0.3834, -0.0889, -0.1568, -0.3420, -0.1257,  0.9254],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 728.05it/s]


epoch: 98, train_loss: 4.190544605255127, val_metric: 0.2141065085934349


100%|██████████| 1/1 [00:00<00:00, 330.57it/s]


tensor([-0.3828, -0.0885, -0.1566, -0.3408, -0.1249,  0.9281],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 705.52it/s]

epoch: 99, train_loss: 4.183767318725586, val_metric: 0.20329048614971318


In [356]:
epoch_losses

[17.493484497070312]

Baby Old Training Loop

In [383]:
import pyepo

feat, cost_true, cost, eps = sp_grid_mike_neurips.genData(num_data + 200, 
                                                     num_feat, 
                                                     grid, 
                                                     ep_type, 
                                                     deg, 
                                                     e, 
                                                     seed=indices_arr[trial])
x_train, x_val, c_train, c_val = train_test_split(feat, cost, test_size=200, random_state=42)
x_test, c_test, c_hat_test, eps_test = sp_grid_mike_neurips.genData(10000, 
                                                          num_feat, 
                                                          grid, 
                                                          ep_type, 
                                                          deg, 
                                                          e, 
                                                          seed=indices_arr_test[trial])

old_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])
old_model.linear = copy.deepcopy(predmodel.linear)
print(old_model.linear.weight[0])

optmodel_old = sp_grid_mike_neurips.shortestPathModel()
old_loss_fn = SPOPlus2(optmodel_old)

optimizer = torch.optim.Adam(old_model.parameters(), lr=0.01)
# build dataset
dataset = pyepo.data.dataset.optDataset(optmodel_old, x_train[:,:-1], c_train)
loader_train = DataLoader(dataset, batch_size=200, shuffle=True)    

tensor([-0.3895,  0.1444, -0.3851, -0.3101, -0.0109,  0.3007],
       grad_fn=<SelectBackward0>)
Num of cores: 1
Optimizing for optDataset...


100%|██████████| 200/200 [00:00<00:00, 1052.83it/s]


In [384]:
# train mode
old_model.train()
# init log
loss_log = [['trial', 'n', 'epoch', 'loss_name', 'regret', 'val_regret']]
loss_name = 'SPO+'
for epoch in range(100):
    
    batch_loss = []
    for i, data in enumerate(loader_train):
        x, c, w, z = data
        w = w.reshape(w.shape[0], -1)
        z = z.reshape(z.shape[0], -1)
        
        cp = old_model(x)
        loss = old_loss_fn(cp, c, w, z)
        

        # backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        batch_loss.append(loss.item())

    print(old_model.linear.weight[0])
    train_regret = sum(batch_loss)
    regret = regret_func(old_model, torch.FloatTensor(x_test[:,:-1]), torch.FloatTensor(c_test))
    val_regret = regret_func(old_model, torch.FloatTensor(x_val[:,:-1]), torch.FloatTensor(c_val))

    loss_log.append([trial, num_data, epoch, loss_name, regret, val_regret])

    print(
        "Epoch {:2},  Train_Regret: {}, Val_Regret: {:7.4f}%, Regret: {:7.4f}%".format(epoch + 1, train_regret,
                                                                                           val_regret * 100,
                                                                                           regret * 100))


tensor([-0.3795,  0.1344, -0.3751, -0.3201, -0.0209,  0.3107],
       grad_fn=<SelectBackward0>)
Epoch  1,  Train_Regret: 17.493484497070312, Val_Regret: 53.8790%, Regret: 49.1503%
tensor([-0.3714,  0.1244, -0.3651, -0.3298, -0.0309,  0.3202],
       grad_fn=<SelectBackward0>)
Epoch  2,  Train_Regret: 16.78026580810547, Val_Regret: 51.8425%, Regret: 47.1263%
tensor([-0.3660,  0.1144, -0.3551, -0.3358, -0.0407,  0.3299],
       grad_fn=<SelectBackward0>)
Epoch  3,  Train_Regret: 16.084392547607422, Val_Regret: 49.8255%, Regret: 44.9284%
tensor([-0.3653,  0.1044, -0.3451, -0.3390, -0.0503,  0.3397],
       grad_fn=<SelectBackward0>)
Epoch  4,  Train_Regret: 15.414484977722168, Val_Regret: 45.8209%, Regret: 42.1496%
tensor([-0.3689,  0.0945, -0.3351, -0.3377, -0.0599,  0.3494],
       grad_fn=<SelectBackward0>)
Epoch  5,  Train_Regret: 14.766684532165527, Val_Regret: 43.3121%, Regret: 39.2565%
tensor([-0.3657,  0.0845, -0.3251, -0.3331, -0.0693,  0.3591],
       grad_fn=<SelectBackward0>)

In [385]:
regret

0.04638737440244818

### Verify the Regret Calc

Old Regret

In [435]:
old_reg_func_old_mod = regret_func(old_model, torch.FloatTensor(x_test[:,:-1]), torch.FloatTensor(c_hat_test))
old_reg_func_new_mod = regret_func(new_model, torch.FloatTensor(x_test[:,:-1]), torch.FloatTensor(c_hat_test))

old_reg_func_old_mod, old_reg_func_new_mod

(0.08560629393454147, 0.08560629393454147)

In [427]:
c_hat_test, final_data_test['true_cost']

(tensor([[1.3985, 1.7580, 3.2470,  ..., 3.2330, 1.5450, 1.7464],
         [2.3881, 1.4507, 2.2957,  ..., 2.9421, 2.2133, 1.5494],
         [1.8591, 1.8944, 4.6037,  ..., 2.9546, 2.8156, 2.2623],
         ...,
         [2.0214, 2.2908, 1.9479,  ..., 2.8776, 1.7721, 1.4501],
         [1.7199, 1.8696, 3.1003,  ..., 3.4000, 1.7542, 2.1117],
         [2.5083, 2.4716, 2.1675,  ..., 4.1673, 1.6614, 1.6436]]),
 array([[1.39848442, 1.75802185, 3.24695078, ..., 3.23298268, 1.54500231,
         1.7464299 ],
        [2.38808872, 1.45070565, 2.29568997, ..., 2.94207769, 2.21333371,
         1.54944921],
        [1.85908374, 1.89436551, 4.60370222, ..., 2.95460682, 2.81563494,
         2.26229281],
        ...,
        [2.02139322, 2.2907848 , 1.94794872, ..., 2.87761556, 1.77207911,
         1.4501351 ],
        [1.7198845 , 1.8695826 , 3.10034075, ..., 3.39997981, 1.75416737,
         2.11173819],
        [2.50827179, 2.47164675, 2.16751198, ..., 4.16734951, 1.66135962,
         1.64358464]]))

In [429]:
x = torch.FloatTensor(x_test[:,:-1])
c = torch.FloatTensor(c_hat_test)
# evaluate
new_model.eval()
with torch.no_grad():  # no grad
    cp = new_model(x) #.to("cpu").detach().numpy()

sol_cp, obj_cp = shortest_path_solver(cp, 5)
sol_c, obj_c = shortest_path_solver(c, 5)
out_obj_cp = torch.sum(sol_cp * c)
out_obj_c = torch.sum(sol_c * c)

torch.sum(out_obj_cp - out_obj_c).item()/(torch.sum(abs(out_obj_c)).item() + 1e-7)


0.08560629393454147

New Regret

In [404]:
old_cp = old_model(torch.tensor(final_data_test['X'], dtype=torch.float32))
new_cp = new_model(torch.tensor(final_data_test['X'], dtype=torch.float32))
(new_cp - old_cp).abs().mean()

False

In [436]:
new_reg_func_old_mod = decision_regret(pred_cost=old_cp,
                true_cost=final_data_test['true_cost'],
                true_obj=final_data_test['true_obj'],
                optmodel=optmodel,
                minimize=True)

new_reg_func_new_mod = decision_regret(pred_cost=new_cp,
                true_cost=final_data_test['true_cost'],
                true_obj=final_data_test['true_obj'],
                optmodel=optmodel,
                minimize=True)

In [437]:
new_reg_func_old_mod, new_reg_func_new_mod

(0.04638751375241514, 0.04638751375241514)

In [430]:
final_data_test.keys()

dict_keys(['X', 'true_cost', 'true_sol', 'true_obj'])

In [410]:
w_hat, z_hat = optmodel(new_cp)
    
# To ensure consistency, convert everything into a pytorch tensor
w_hat = torch.tensor(w_hat, dtype=torch.float32)
z_hat = torch.tensor(z_hat, dtype=torch.float32)
true_cost = torch.tensor(final_data_test['true_cost'], dtype=torch.float32)
true_obj = torch.tensor(final_data_test['true_obj'], dtype=torch.float32)

# objective value of pred_cost induced solution (w_hat) based on true cost
obj_hat = (w_hat * true_cost).sum(axis=1, keepdim=True)
    
regret = (obj_hat - true_obj).sum()
minimize=True
if not minimize:
    regret = -regret

opt_obj_sum = torch.sum(torch.abs(true_obj)).item() + 1e-7
regret.item() / opt_obj_sum

/tmp/SLURM_27423203/ipykernel_37376/2143074558.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w_hat = torch.tensor(w_hat, dtype=torch.float32)
/tmp/SLURM_27423203/ipykernel_37376/2143074558.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z_hat = torch.tensor(z_hat, dtype=torch.float32)
/tmp/SLURM_27423203/ipykernel_37376/2143074558.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  true_obj = torch.tensor(final_data_test['true_obj'], dtype=torch.float32)


0.08560642662104108

Given same prediction - same optimal solution?

In [415]:
(sol_cp == w_hat).all()

tensor(True)

In [422]:
(obj_cp - z_hat).abs().max()

tensor(9.5367e-07)

In [424]:
true_obj, obj_c

(tensor([[14.0896],
         [14.6872],
         [16.2804],
         ...,
         [15.2295],
         [15.1068],
         [15.2983]]),
 tensor([[15.9502],
         [16.0000],
         [16.0000],
         ...,
         [16.0000],
         [16.0000],
         [16.0000]]))

# Initialize Data

# Training Loop

In [202]:
# Prediction Model
pred_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])
initial_weights = copy.deepcopy(pred_model.state_dict())

model = LinearRegression(input_dim=train_dict_old['X'].shape[1],
                 output_dim=train_dict_old['true_cost'].shape[1])
model.load_state_dict(copy.deepcopy(initial_weights))

model_2 = LinearRegression(input_dim=train_dict_old['X'].shape[1],
                 output_dim=train_dict_old['true_cost'].shape[1])
model_2.load_state_dict(copy.deepcopy(initial_weights))


<All keys matched successfully>

In [203]:
pred_model.linear.weight[0]

tensor([ 0.0941, -0.3390, -0.3272,  0.0868,  0.0219, -0.2847],
       grad_fn=<SelectBackward0>)

### New Data

In [175]:
generated_data = genData(num_data=num_data+200,
        num_features=num_feat, 
        grid=grid, 
        deg=deg, 
        noise_type=ep_type,
        noise_width=e,
        seed=indices_arr[trial],     
        plant_edges=plant_edge,
        planted_good_pwl_params=planted_good_pwl_params,
        planted_bad_pwl_params=planted_bad_pwl_params)
sol, obj = shortest_path_solver(costs=generated_data['cost'], size=5)
final_data = {'X':generated_data['feat'],
              'true_cost':generated_data['cost'],
              'true_sol':sol,
              'true_obj':obj}

# Splitting each input in the same way
train_dict = {}
val_dict = {}

for key, value in final_data.items():
    train_data, val_data = train_test_split(value, test_size=200, random_state=42)
    train_dict[key] = train_data
    val_dict[key] = val_data
    
# test data
generated_data_test = genData(num_data=10000,
        num_features=num_feat, 
        grid=grid, 
        deg=deg, 
        noise_type=ep_type,
        noise_width=e,
        seed=indices_arr_test[trial],     
        plant_edges=plant_edge,
        planted_good_pwl_params=planted_good_pwl_params,
        planted_bad_pwl_params=planted_bad_pwl_params)
sol_test, obj_test = shortest_path_solver(costs=generated_data_test['cost'], size=5)
final_data_test = {'X':generated_data_test['feat'],
              'true_cost':generated_data_test['cost'],
              'true_sol':sol_test,
              'true_obj':obj_test}

2024-11-13 13:15:41,508 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 10 11 12 13 14 17 18 19 20 21 22 25 26 27 28 29 32 33 34 37]
2024-11-13 13:15:41,508 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 10 11 12 13 14 17 18 19 20 21 22 25 26 27 28 29 32 33 34 37]
2024-11-13 13:15:41,513 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.0
2024-11-13 13:15:41,513 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.0
2024-11-13 13:15:41,513 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.55
2024-11-13 13:15:41,513 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.55
2024-11-13 13:15:41,538 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 

In [204]:
# Deep copy the model
print(model.linear.weight[0])
# optimization solver
optmodel = partial(shortest_path_solver,size=5)

# loss function
loss_fn = SPOPlus(optmodel=optmodel)

metrics, trained_model = train(pred_model=pred_model,
                optmodel=optmodel,
                loss_fn=loss_fn,
                train_data_dict=train_dict,
                val_data_dict=val_dict,
                dataloader_params={'batch_size':200, 'shuffle':True},
                num_epochs=100,
                lr=0.01,
                scheduler_params=None, #{'step_size': 10, 'gamma': 0.1},
                minimization=True)

tensor([ 0.0941, -0.3390, -0.3272,  0.0868,  0.0219, -0.2847],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 676.17it/s]
2024-11-13 13:23:31,393 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 14.1853666305542, val_metric: 0.2569626234293161
2024-11-13 13:23:31,393 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 14.1853666305542, val_metric: 0.2569626234293161
100%|██████████| 1/1 [00:00<00:00, 688.38it/s]
2024-11-13 13:23:31,401 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 13.587915420532227, val_metric: 0.2531696263922039
2024-11-13 13:23:31,401 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 13.587915420532227, val_metric: 0.2531696263922039
100%|██████████| 1/1 [00:00<00:00, 705.87it/s]
2024-11-13 13:23:31,410 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 13.024239540100098, val_metric: 0.2137474692494163
2024-11-13 13:23:31,410 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 13.024239540100098, val_metric: 0.2137474692494163
100%|██████████| 

In [212]:
test_regret = calc_test_regret(pred_model=trained_model,
                               test_data_dict=final_data_test, #final_data_te,
                               optmodel=optmodel)
print(test_regret)

0.08402777103613965


### Old Data

In [214]:
feat, cost_true, cost, eps = sp_grid_mike_neurips.genData(num_data + 200, 
                                                     num_feat, 
                                                     grid, 
                                                     ep_type, 
                                                     deg, 
                                                     e, 
                                                     seed=indices_arr[trial])
x_train, x_val, c_train, c_val = train_test_split(feat, cost, test_size=200, random_state=42)
x_test, c_test, c_hat_test, eps_test = sp_grid_mike_neurips.genData(10000, 
                                                          num_feat, 
                                                          grid, 
                                                          ep_type, 
                                                          deg, 
                                                          e, 
                                                          seed=indices_arr_test[trial])

# train
sol_tr, obj_tr = shortest_path_solver(costs=c_train, size=5)
train_dict_old = {'X':x_train, #[:,:-1],
              'true_cost':c_train,
              'true_sol':sol_tr,
              'true_obj':obj_tr}
# val
sol_v, obj_v = shortest_path_solver(costs=c_val, size=5)
val_dict_old = {'X':x_val, #[:,:-1],
              'true_cost':c_val,
              'true_sol':sol_v,
              'true_obj':obj_v}

# test
sol_te, obj_te = shortest_path_solver(costs=c_hat_test, size=5)
final_data_te = {'X':x_test, #[:,:-1],
              'true_cost':c_hat_test,
              'true_sol':sol_te,
              'true_obj':obj_te}

In [215]:
# Deep copy the model
model_2 = LinearRegression(input_dim=train_dict_old['X'].shape[1],
                 output_dim=train_dict_old['true_cost'].shape[1])
print(model_2.linear.weight[0])
# optimization solver
optmodel_2 = partial(shortest_path_solver,size=5)

# loss function
loss_fn_2 = SPOPlus(optmodel=optmodel)

metrics_2, trained_model_2 = train(pred_model=model_2,
                optmodel=optmodel_2,
                loss_fn=loss_fn_2,
                train_data_dict=train_dict_old,
                val_data_dict=val_dict_old,
                dataloader_params={'batch_size':200, 'shuffle':True},
                num_epochs=100,
                lr=0.01,
                scheduler_params=None, #{'step_size': 10, 'gamma': 0.1},
                minimization=True)

tensor([-0.2872, -0.1867, -0.1686,  0.0504,  0.2973, -0.0260, -0.0786],
       grad_fn=<SelectBackward0>)


100%|██████████| 1/1 [00:00<00:00, 586.45it/s]
2024-11-13 13:26:29,649 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 15.820372581481934, val_metric: 0.5183820143070256
2024-11-13 13:26:29,649 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 15.820372581481934, val_metric: 0.5183820143070256
100%|██████████| 1/1 [00:00<00:00, 681.23it/s]
2024-11-13 13:26:29,662 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 14.878893852233887, val_metric: 0.5010580228972782
2024-11-13 13:26:29,662 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 14.878893852233887, val_metric: 0.5010580228972782
100%|██████████| 1/1 [00:00<00:00, 687.82it/s]
2024-11-13 13:26:29,670 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 13.96707534790039, val_metric: 0.4288215955036147
2024-11-13 13:26:29,670 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 13.96707534790039, val_metric: 0.4288215955036147
100%|██████████

In [216]:
test_regret = calc_test_regret(pred_model=trained_model_2,
                               test_data_dict=final_data_te, #final_data_te,
                               optmodel=optmodel)
print(test_regret)

0.07610093450950099


In [40]:
c_train.shape

torch.Size([200, 40])

In [22]:
feat.shape

torch.Size([400, 7])

In [439]:
generated_data = genData(num_data=num_data+200,
        num_features=num_feat, 
        grid=grid, 
        deg=deg, 
        noise_type=ep_type,
        noise_width=e,
        seed=indices_arr[trial],     
        plant_edges=plant_edge,
        planted_good_pwl_params=planted_good_pwl_params,
        planted_bad_pwl_params=planted_bad_pwl_params)
sol, obj = shortest_path_solver(costs=generated_data['cost'], size=5)
final_data = {'X':generated_data['feat'],
              'true_cost':generated_data['cost'],
              'true_sol':sol,
              'true_obj':obj}

# 1. Data - features, costs
# 2. Prediction model/plugin
# 3. solver/optimization
# 4. loss function (optional - try out everything)

# def aggregateData(X, y, loss_fn, solver):

#     if loss_fn...
#         sol, obj = solver(costs=y)
#         final_data = {'X':X,
#                       'true_cost':y,
#                       'true_sol':sol,
#                       'true_obj':obj}


# custom user - unique loss function
# TODO: how to combine it with the pipeline?
# 1. Single pipeline
# 2. data first, then losses

# experiment code loop - call the pipeline, custom behavior..
# single pipeline

# custom behavior - pipeline


# test data
generated_data_test = genData(num_data=10000,
        num_features=num_feat, 
        grid=grid, 
        deg=deg, 
        noise_type=ep_type,
        noise_width=e,
        seed=indices_arr[trial],     
        plant_edges=plant_edge,
        planted_good_pwl_params=planted_good_pwl_params,
        planted_bad_pwl_params=planted_bad_pwl_params)
sol_test, obj_test = shortest_path_solver(costs=generated_data_test['cost_true'], size=5)
final_data_test = {'X':generated_data_test['feat'],
              'true_cost':generated_data_test['cost_true'],
              'true_sol':sol_test,
              'true_obj':obj_test}

2024-11-13 16:25:28,526 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 10 11 12 13 14 17 18 19 20 21 22 25 26 27 28 29 32 33 34 37]
2024-11-13 16:25:28,526 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 10 11 12 13 14 17 18 19 20 21 22 25 26 27 28 29 32 33 34 37]
2024-11-13 16:25:28,527 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.0
2024-11-13 16:25:28,527 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.0
2024-11-13 16:25:28,528 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.55
2024-11-13 16:25:28,528 - decision_learning.data.shortest_path_grid - DEBUG - chg_pt: 0.55
2024-11-13 16:25:28,554 - decision_learning.data.shortest_path_grid - DEBUG - good_bad_edges: [ 1  4  9 16 24 31 36 39  0  3  8 15 23 30 35 38], remain_edges: [ 2  5  6  7 

Split data into train and validation set

In [440]:
# Splitting each input in the same way
train_dict = {}
val_dict = {}

for key, value in final_data.items():
    train_data, val_data = train_test_split(value, test_size=200, random_state=42)
    train_dict[key] = train_data
    val_dict[key] = val_data


# double checking the splitting is done correctly
# Splitting indices
indices = np.arange(len(next(iter(final_data.values()))))
train_indices, val_indices = train_test_split(indices, test_size=200, random_state=42)

for key in final_data.keys():
    train_same = (final_data[key][train_indices] == train_dict[key]).all()
    val_same = (final_data[key][val_indices] == val_dict[key]).all()
    print(f'{key}: {train_same}, {val_same}')

X: True, True
true_cost: True, True
true_sol: True, True
true_obj: True, True


# Training Loop

Initialize Inputs to Trainining Loop

In [441]:
# Prediction Model
pred_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])

# optimization solver
optmodel = partial(shortest_path_solver,size=5)

# loss function
loss_fn = SPOPlus(optmodel=optmodel)

# training, validation data
train_data_dict = train_dict
val_data_dict = val_dict

In [442]:
metrics, trained_model = train(pred_model=pred_model,
                optmodel=optmodel,
                loss_fn=loss_fn,
                train_data_dict=train_data_dict,
                val_data_dict=val_data_dict,
                dataloader_params={'batch_size':200, 'shuffle':True},
                num_epochs=100,
                lr=0.01,
                scheduler_params=None, #{'step_size': 10, 'gamma': 0.1},
                minimization=True)

100%|██████████| 1/1 [00:00<00:00, 673.24it/s]
2024-11-13 16:25:40,572 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 14.039381980895996, val_metric: 0.364844584815951
2024-11-13 16:25:40,572 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 14.039381980895996, val_metric: 0.364844584815951
100%|██████████| 1/1 [00:00<00:00, 235.64it/s]
2024-11-13 16:25:40,582 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 13.375387191772461, val_metric: 0.35583657445013506
2024-11-13 16:25:40,582 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 13.375387191772461, val_metric: 0.35583657445013506
100%|██████████| 1/1 [00:00<00:00, 729.82it/s]
2024-11-13 16:25:40,590 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 12.743906021118164, val_metric: 0.3256780603369004
2024-11-13 16:25:40,590 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 12.743906021118164, val_metric: 0.3256780603369004
100%|████████

In [443]:
metrics

epoch  train_loss  val_metric
0       0   14.039382    0.364845
1       1   13.375387    0.355837
2       2   12.743906    0.325678
3       3   12.143230    0.313259
4       4   11.577141    0.312537
..    ...         ...         ...
95     95    4.125385    0.206730
96     96    4.120779    0.196237
97     97    4.116006    0.191460
98     98    4.111292    0.209852
99     99    4.107181    0.207163

[100 rows x 3 columns]

In [138]:
val_dict['X'].shape

(200, 6)

In [444]:
val_regret = calc_test_regret(pred_model=trained_model,
                               test_data_dict=val_dict,
                               optmodel=optmodel)
print(val_regret)

0.08272489650178559


/home1/yongpeng/decision-focused-learning/src/decision_learning/modeling/val_metrics.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w_hat = torch.tensor(w_hat, dtype=torch.float32)
/home1/yongpeng/decision-focused-learning/src/decision_learning/modeling/val_metrics.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z_hat = torch.tensor(z_hat, dtype=torch.float32)
/home1/yongpeng/decision-focused-learning/src/decision_learning/modeling/val_metrics.py:29: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  true_obj = torch.tensor(true_obj

In [445]:
test_regret = calc_test_regret(pred_model=trained_model,
                               test_data_dict=final_data_test, #final_data_te,
                               optmodel=optmodel)
print(test_regret)

0.045393637861943975


## MSE

In [27]:
# Prediction Model
pred_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])

# optimization solver
optmodel = partial(shortest_path_solver,size=5)

# loss function
loss_fn = nn.MSELoss()

# training, validation data
train_data_dict = train_dict
train_data_dict.update({'target':train_dict['true_cost']}) # extra input key needed for loss function

val_data_dict = val_dict

In [29]:
metrics, trained_model = train(pred_model=pred_model,
                optmodel=optmodel,
                loss_fn=loss_fn,
                train_data_dict=train_data_dict,
                val_data_dict=val_data_dict,
                num_epochs=100,
                lr=0.1,
                scheduler_params={'step_size': 10, 'gamma': 0.1},
                minimization=True)

100%|██████████| 12/12 [00:00<00:00, 3463.98it/s]
2024-11-06 09:09:21,646 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 1.8876804921362136, val_metric: 0.2392113968593179
2024-11-06 09:09:21,646 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 1.8876804921362136, val_metric: 0.2392113968593179
100%|██████████| 12/12 [00:00<00:00, 3477.38it/s]
2024-11-06 09:09:21,683 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 0.765940973493788, val_metric: 0.2152039387182229
2024-11-06 09:09:21,683 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 0.765940973493788, val_metric: 0.2152039387182229
100%|██████████| 12/12 [00:00<00:00, 3445.72it/s]
2024-11-06 09:09:21,720 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 0.6751075949933794, val_metric: 0.21910987352311345
2024-11-06 09:09:21,720 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 0.6751075949933794, val_metric: 0.21910987352311345
100%

In [30]:
test_regret = calc_test_regret(pred_model=pred_model,
                               test_data_dict=final_data_test,
                               optmodel=optmodel)
print(test_regret)

0.08562925913696434


## Cosine Loss

In [40]:
# Prediction Model
pred_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                 output_dim=train_dict['true_cost'].shape[1])

# optimization solver
optmodel = partial(shortest_path_solver,size=5)

# loss function
loss_fn = nn.CosineEmbeddingLoss()

# training, validation data
train_data_dict = train_dict
train_data_dict.update({'input2':train_dict['true_cost'], 
                       'target':torch.ones(train_dict['true_cost'].shape[0])}) # extra input key needed for loss function

val_data_dict = val_dict

In [41]:
metrics, trained_model = train(pred_model=pred_model,
                optmodel=optmodel,
                loss_fn=loss_fn,
                train_data_dict=train_data_dict,
                val_data_dict=val_data_dict,
                num_epochs=100,
                lr=0.1,
                scheduler_params={'step_size': 10, 'gamma': 0.1},
                minimization=True)

100%|██████████| 12/12 [00:00<00:00, 3458.51it/s]
2024-11-06 09:18:08,838 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 0.07857334117094676, val_metric: 0.15394632031310854
2024-11-06 09:18:08,838 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 0.07857334117094676, val_metric: 0.15394632031310854
100%|██████████| 12/12 [00:00<00:00, 3487.02it/s]
2024-11-06 09:18:08,884 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 0.023548006556100315, val_metric: 0.16055482282145492
2024-11-06 09:18:08,884 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 0.023548006556100315, val_metric: 0.16055482282145492
100%|██████████| 12/12 [00:00<00:00, 3498.65it/s]
2024-11-06 09:18:08,931 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 0.022603477413455645, val_metric: 0.1482329970276144
2024-11-06 09:18:08,931 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 0.022603477413455645, val_metric: 0.1482329

In [42]:
test_regret = calc_test_regret(pred_model=pred_model,
                               test_data_dict=final_data_test,
                               optmodel=optmodel)
print(test_regret)

0.06871183614832832


## PG Loss

In [56]:
import decision_learning.modeling.loss
importlib.reload(decision_learning.modeling.loss)
from decision_learning.modeling.loss import PG_Loss

In [50]:
# optimization solver
optmodel = partial(shortest_path_solver,size=5)

# training, validation data
train_data_dict = train_dict
val_data_dict = val_dict

PG Loss Parameters

In [54]:
h_arr = [num_data**-.125, num_data**-.25, num_data**-.5, num_data**-1]
fin_diff_sch = ['B', 'F', 'C']

In [57]:
# loop over PG loss params
PG_results = []
for h in h_arr:
    for f in fin_diff_sch:
        
        print(h, f)
        
        # --- Need to instantiate new loss function and prediction model for each possible setting of PG loss ---   
        # loss function
        loss_fn = PG_Loss(optmodel=optmodel,
                         h=h,
                         finite_diff_type=f)
        # Prediction Model
        pred_model = LinearRegression(input_dim=train_dict['X'].shape[1],
                         output_dim=train_dict['true_cost'].shape[1])
        # ----------------------------------------------------------------------------------------------------------------
        
        metrics, trained_model = train(pred_model=pred_model,
                        optmodel=optmodel,
                        loss_fn=loss_fn,
                        train_data_dict=train_data_dict,
                        val_data_dict=val_data_dict,
                        num_epochs=100,
                        lr=0.1,
                        scheduler_params={'step_size': 10, 'gamma': 0.1},
                        minimization=True)
        test_regret = calc_test_regret(pred_model=pred_model,
                               test_data_dict=final_data_test,
                               optmodel=optmodel)

        # add current setting results to overall results
        cur_res = {'h':h, 'finite_diff_sch': f, 'test_regret': test_regret}
        PG_results.append(cur_res)

# convert to pandas dataframe
PG_results = pd.DataFrame(PG_results)


0.3976353643835253 B


100%|██████████| 12/12 [00:00<00:00, 3474.98it/s]
2024-11-06 10:50:49,084 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 23.011095428466795, val_metric: 0.6255135366346355
2024-11-06 10:50:49,084 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 23.011095428466795, val_metric: 0.6255135366346355
100%|██████████| 12/12 [00:00<00:00, 3451.16it/s]
2024-11-06 10:50:49,215 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.265939500596787, val_metric: 0.6662045242176788
2024-11-06 10:50:49,215 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.265939500596787, val_metric: 0.6662045242176788
100%|██████████| 12/12 [00:00<00:00, 3441.72it/s]
2024-11-06 10:50:49,345 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.35850109524197, val_metric: 0.6505704453340708
2024-11-06 10:50:49,345 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.35850109524197, val_metric: 0.6505704453340708
100%|█

0.3976353643835253 F


100%|██████████| 12/12 [00:00<00:00, 3494.53it/s]
2024-11-06 10:51:02,077 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.870707575480143, val_metric: 0.663972930745743
2024-11-06 10:51:02,077 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.870707575480143, val_metric: 0.663972930745743
100%|██████████| 12/12 [00:00<00:00, 3478.83it/s]
2024-11-06 10:51:02,207 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.582617653740776, val_metric: 0.6422090023064015
2024-11-06 10:51:02,207 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.582617653740776, val_metric: 0.6422090023064015
100%|██████████| 12/12 [00:00<00:00, 3482.20it/s]
2024-11-06 10:51:02,336 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.654586283365884, val_metric: 0.6620179739716615
2024-11-06 10:51:02,336 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.654586283365884, val_metric: 0.6620179739716615
100%|█

0.3976353643835253 C


100%|██████████| 12/12 [00:00<00:00, 3476.42it/s]
2024-11-06 10:51:15,064 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.92938838534885, val_metric: 0.694055929864017
2024-11-06 10:51:15,064 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.92938838534885, val_metric: 0.694055929864017
100%|██████████| 12/12 [00:00<00:00, 3464.46it/s]
2024-11-06 10:51:15,194 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.450037892659505, val_metric: 0.6963111930570773
2024-11-06 10:51:15,194 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.450037892659505, val_metric: 0.6963111930570773
100%|██████████| 12/12 [00:00<00:00, 3437.95it/s]
2024-11-06 10:51:15,325 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.534807374742297, val_metric: 0.6735117269896924
2024-11-06 10:51:15,325 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.534807374742297, val_metric: 0.6735117269896924
100%|███

0.15811388300841897 B


100%|██████████| 12/12 [00:00<00:00, 3485.09it/s]
2024-11-06 10:51:28,037 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.604107962714302, val_metric: 0.6668400587641051
2024-11-06 10:51:28,037 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.604107962714302, val_metric: 0.6668400587641051
100%|██████████| 12/12 [00:00<00:00, 3487.74it/s]
2024-11-06 10:51:28,167 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.038161595662434, val_metric: 0.6615401699865622
2024-11-06 10:51:28,167 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.038161595662434, val_metric: 0.6615401699865622
100%|██████████| 12/12 [00:00<00:00, 3463.03it/s]
2024-11-06 10:51:28,296 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.27036450703939, val_metric: 0.6751100667234474
2024-11-06 10:51:28,296 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.27036450703939, val_metric: 0.6751100667234474
100%|█

0.15811388300841897 F


100%|██████████| 12/12 [00:00<00:00, 3485.33it/s]
2024-11-06 10:51:41,001 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.34955622355143, val_metric: 0.6982016283001277
2024-11-06 10:51:41,001 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.34955622355143, val_metric: 0.6982016283001277
100%|██████████| 12/12 [00:00<00:00, 3504.01it/s]
2024-11-06 10:51:41,131 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.70132369995117, val_metric: 0.6831144365491411
2024-11-06 10:51:41,131 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.70132369995117, val_metric: 0.6831144365491411
100%|██████████| 12/12 [00:00<00:00, 3470.91it/s]
2024-11-06 10:51:41,260 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.741004308064777, val_metric: 0.6836601579353259
2024-11-06 10:51:41,260 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.741004308064777, val_metric: 0.6836601579353259
100%|███

0.15811388300841897 C


100%|██████████| 12/12 [00:00<00:00, 3432.33it/s]
2024-11-06 10:51:54,029 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.759136793348524, val_metric: 0.687248528205514
2024-11-06 10:51:54,029 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 22.759136793348524, val_metric: 0.687248528205514
100%|██████████| 12/12 [00:00<00:00, 3470.43it/s]
2024-11-06 10:51:54,160 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.062710316975913, val_metric: 0.6881737253991072
2024-11-06 10:51:54,160 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 23.062710316975913, val_metric: 0.6881737253991072
100%|██████████| 12/12 [00:00<00:00, 3441.48it/s]
2024-11-06 10:51:54,290 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.14165564643012, val_metric: 0.6957650155092434
2024-11-06 10:51:54,290 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 23.14165564643012, val_metric: 0.6957650155092434
100%|███

0.025 B


100%|██████████| 12/12 [00:00<00:00, 3462.08it/s]
2024-11-06 10:52:07,039 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.21046863132053, val_metric: 0.6104436283416863
2024-11-06 10:52:07,039 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.21046863132053, val_metric: 0.6104436283416863
100%|██████████| 12/12 [00:00<00:00, 3476.18it/s]
2024-11-06 10:52:07,169 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 21.984708404541017, val_metric: 0.6468948975042804
2024-11-06 10:52:07,169 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 21.984708404541017, val_metric: 0.6468948975042804
100%|██████████| 12/12 [00:00<00:00, 3457.08it/s]
2024-11-06 10:52:07,299 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.399849616156683, val_metric: 0.6539994631348464
2024-11-06 10:52:07,299 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.399849616156683, val_metric: 0.6539994631348464
100%|█

0.025 F


100%|██████████| 12/12 [00:00<00:00, 3165.31it/s]
2024-11-06 10:52:20,077 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.84036776224772, val_metric: 0.6452746113267419
2024-11-06 10:52:20,077 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.84036776224772, val_metric: 0.6452746113267419
100%|██████████| 12/12 [00:00<00:00, 3480.03it/s]
2024-11-06 10:52:20,209 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.268305842081705, val_metric: 0.6749856359625034
2024-11-06 10:52:20,209 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.268305842081705, val_metric: 0.6749856359625034
100%|██████████| 12/12 [00:00<00:00, 3491.13it/s]
2024-11-06 10:52:20,342 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.50905621846517, val_metric: 0.675860908797836
2024-11-06 10:52:20,342 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.50905621846517, val_metric: 0.675860908797836
100%|█████

0.025 C


100%|██████████| 12/12 [00:00<00:00, 3529.57it/s]
2024-11-06 10:52:33,350 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.91272850036621, val_metric: 0.6914831781631956
2024-11-06 10:52:33,350 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.91272850036621, val_metric: 0.6914831781631956
100%|██████████| 12/12 [00:00<00:00, 3558.01it/s]
2024-11-06 10:52:33,483 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.339214706420897, val_metric: 0.6962246237130072
2024-11-06 10:52:33,483 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 22.339214706420897, val_metric: 0.6962246237130072
100%|██████████| 12/12 [00:00<00:00, 3537.26it/s]
2024-11-06 10:52:33,615 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.33821593390571, val_metric: 0.6996225718370175
2024-11-06 10:52:33,615 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 22.33821593390571, val_metric: 0.6996225718370175
100%|███

0.000625 B


100%|██████████| 12/12 [00:00<00:00, 3537.51it/s]
2024-11-06 10:52:46,625 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 19.098456202612983, val_metric: 0.48393195932385197
2024-11-06 10:52:46,625 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 19.098456202612983, val_metric: 0.48393195932385197
100%|██████████| 12/12 [00:00<00:00, 3549.23it/s]
2024-11-06 10:52:46,757 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 19.973195393880207, val_metric: 0.5096618078249383
2024-11-06 10:52:46,757 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 19.973195393880207, val_metric: 0.5096618078249383
100%|██████████| 12/12 [00:00<00:00, 3534.77it/s]
2024-11-06 10:52:46,890 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 20.22644725375705, val_metric: 0.5080517599421902
2024-11-06 10:52:46,890 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 20.22644725375705, val_metric: 0.5080517599421902
100%

0.000625 F


100%|██████████| 12/12 [00:00<00:00, 3539.25it/s]
2024-11-06 10:52:59,903 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.449234347873265, val_metric: 0.3697886319169076
2024-11-06 10:52:59,903 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.449234347873265, val_metric: 0.3697886319169076
100%|██████████| 12/12 [00:00<00:00, 3539.00it/s]
2024-11-06 10:53:00,036 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 18.69632191128201, val_metric: 0.3699657493483205
2024-11-06 10:53:00,036 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 18.69632191128201, val_metric: 0.3699657493483205
100%|██████████| 12/12 [00:00<00:00, 3537.26it/s]
2024-11-06 10:53:00,168 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 18.69419576856825, val_metric: 0.3757900466261107
2024-11-06 10:53:00,168 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 18.69419576856825, val_metric: 0.3757900466261107
100%|███

0.000625 C


100%|██████████| 12/12 [00:00<00:00, 3523.39it/s]
2024-11-06 10:53:12,740 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.136268191867405, val_metric: 0.5513897522055999
2024-11-06 10:53:12,740 - decision_learning.modeling.train - INFO - epoch: 0, train_loss: 21.136268191867405, val_metric: 0.5513897522055999
100%|██████████| 12/12 [00:00<00:00, 3541.49it/s]
2024-11-06 10:53:12,869 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 20.29042994181315, val_metric: 0.5520808371039588
2024-11-06 10:53:12,869 - decision_learning.modeling.train - INFO - epoch: 1, train_loss: 20.29042994181315, val_metric: 0.5520808371039588
100%|██████████| 12/12 [00:00<00:00, 3535.77it/s]
2024-11-06 10:53:12,998 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 20.282528347439236, val_metric: 0.5514522970361518
2024-11-06 10:53:12,998 - decision_learning.modeling.train - INFO - epoch: 2, train_loss: 20.282528347439236, val_metric: 0.5514522970361518
100%|█

NameError: name 'pd' is not defined

In [61]:
PG_results

h finite_diff_sch  test_regret
0   0.397635               B     0.766241
1   0.397635               F     0.703595
2   0.397635               C     0.760432
3   0.158114               B     0.742369
4   0.158114               F     0.732630
5   0.158114               C     0.732590
6   0.025000               B     0.715896
7   0.025000               F     0.711148
8   0.025000               C     0.703984
9   0.000625               B     0.572492
10  0.000625               F     0.379600
11  0.000625               C     0.508987